springdoc:
  api-docs:
    enabled: true
  group-configs:
    - group: 文件模块
      paths-to-match: /exam/api/file/**
    - group: 用户模块
      paths-to-match: /exam/api/user/**
    - group: 系统模块
      paths-to-match: /exam/api/sys/**
    - group: 考试模块
      paths-to-match: /exam/api/exam/**
    - group: 试卷模块
      paths-to-match: /exam/api/paper/**
    - group: 试题模块
      paths-to-match: /exam/api/qu/**
    - group: 题库模块
      paths-to-match: /exam/api/repo/**
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/online_exam?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource

